apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Adjust this as per your requirements
  storageClassName: ebs-sc  # Referencing a StorageClass to provision the storage
